// <auto-generated />
using System;
using IPE.Chatbot.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPE.Chatbot.Persistence.Migrations
{
    [DbContext(typeof(ChatbotDbContext))]
    [Migration("20251026212452_updatefieldtypederechohabiente")]
    partial class updatefieldtypederechohabiente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPE.Chatbot.Domain.Entities.chatBot.DerechohabienteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Afiliacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Flujo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaInteraccion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Derechohabientes");
                });

            modelBuilder.Entity("IPE.Chatbot.Domain.Entities.chatBot.SolicitudesSimulacionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DerechohabienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoSimulacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DerechohabienteId");

                    b.ToTable("SolicitudesSimulacion");
                });

            modelBuilder.Entity("IPE.Chatbot.Domain.Entities.chatBot.SolicitudesSimulacionEntity", b =>
                {
                    b.HasOne("IPE.Chatbot.Domain.Entities.chatBot.DerechohabienteEntity", "Derechohabiente")
                        .WithMany("SolicitudesSimulacion")
                        .HasForeignKey("DerechohabienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Derechohabiente");
                });

            modelBuilder.Entity("IPE.Chatbot.Domain.Entities.chatBot.DerechohabienteEntity", b =>
                {
                    b.Navigation("SolicitudesSimulacion");
                });
#pragma warning restore 612, 618
        }
    }
}
